spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:h2:./db_dev;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 100
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ${custom.data.redis.password}
  h2:
    console:
      enabled: true
  autoconfigure:   # 운영환경에서만 redis를 사용하도록 설정
    exclude:
      #- org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      #- org.springframework.boot.autoconfigure.session.SessionAutoConfiguration   # 세션을 redis에 저장
logging:
  level:
    com.ll.gooHaeYu: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
tossPayments:
  successUrl: "http://localhost:5173/payment/success"
  failUrl: "http://localhost:5173/payment/fail"
firebaseAdminSdkPath: "firebase/goohaeyou-firebase-adminsdk.json"