server:
  port: 8090
spring:
  batch:
    job:
      enabled: false
  profiles:
    active: dev
    include: secret
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  jackson:
    serialization:
      fail-on-empty-beans: false
  threads:
    virtual:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
logging:
  level:
    root: INFO
custom:
  dev:
    cookieDomain: localhost
    frontUrl: "http://${custom.dev.cookieDomain}:5173"
    backUrl: "http://${custom.dev.cookieDomain}:${server.port}"
  prod:
    cookieDomain: www.goohaeyou.site
    frontUrl: "https://${custom.prod.cookieDomain}"
    backUrl: "https://a.goohaeyou.site"
  site:
    cookieDomain: "${custom.dev.cookieDomain}"
    frontUrl: "${custom.dev.frontUrl}"
    backUrl: "${custom.dev.backUrl}"
    name: goohaeyou
tossPayments:
  clientKey: ${tossPayments.apiClientKey}
  secretKey: ${tossPayments.apiSecretKey}
  url: "https://api.tosspayments.com/v1/payments/"
cloud:
  aws:
    credentials:
      accessKey: ${cloud.aws.credentials.accessKey}
      secretKey: ${cloud.aws.credentials.secretKey}
    s3:
      bucketName: ${cloud.aws.s3.bucketName}
    region:
      static: ap-northeast-2
    stack:
      auto: false
