name: aws deploy
on:
  push:
    paths:
      - .github/workflows/deploy-aws.yml
      - back/src/**
      - back/build.gradle
      - back/docker/Dockerfile
      - README.md
      - back/infraScript/**
    branches:
      - dev

permissions:
  contents: write
  packages: write
  actions: write
  deployments: write

jobs:
  makeTagAndRelease:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.create_tag.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Tag 생성
        id: create_tag
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Release 생성
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.create_tag.outputs.new_tag }}
          release_name: Release ${{ steps.create_tag.outputs.new_tag }}
          body: ${{ steps.create_tag.outputs.changelog }}
          draft: false
          prerelease: false
  dockerImagePreparationBuildAndPush:
    name: 도커 이미지 준비, Build & Push
    needs: makeTagAndRelease
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 도커 Buildx 설치
        uses: docker/setup-buildx-action@v2

      - name: 도커 레지스트리 로그인
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Repository OWNER 아이디를 소문자로 변환해 저장
        run: |
          echo "OWNER_LC=${OWNER,,}" >> ${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: application-secret.yml 생성
        env:
          ACTIONS_STEP_DEBUG: true
          APPLICATION_SECRET: ${{ secrets.APPLICATION_SECRET_YML }}
        run: echo "$APPLICATION_SECRET" > back/src/main/resources/application-secret.yml

      - name: 도커 이미지 Build & Push
        uses: docker/build-push-action@v3
        with:
          instance-ids: "i-04750d527ac3ba112"
          context: ./back
          file: ./back/docker/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/goohaeyou:${{ needs.makeTagAndRelease.outputs.tag_name }},
            ghcr.io/${{ env.OWNER_LC }}/goohaeyou:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [ dockerImagePreparationBuildAndPush ]
    steps:
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@master
        id: ssm
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          instance-ids: "i-04750d527ac3ba112"
          working-directory: /
          comment: AWS Zero Downtime Deployment
          command: |
            mkdir -p /docker_projects/goohaeyou
            curl -o /docker_projects/goohaeyou/zero_downtime_deploy.py https://raw.githubusercontent.com/Techit7-11/goohaeyou/dev/back/infraScript/zero_downtime_deploy.py
            chmod +x /docker_projects/goohaeyou/zero_downtime_deploy.py
            /docker_projects/goohaeyou/zero_downtime_deploy.py